#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Purpose: Generates a personalized open-source philosophy statement and saves it to a file

echo "=============================================="
echo "    Open Source Manifesto Generator"
echo "=============================================="
echo "Answer three questions to generate your manifesto."
echo ""

read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# Example alias concept:
# alias ll='ls -la'

echo "==============================================" > "$OUTPUT"
echo "         My Open Source Manifesto" >> "$OUTPUT"
echo "==============================================" >> "$OUTPUT"
echo "Date: $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I believe open-source software represents $FREEDOM." >> "$OUTPUT"
echo "Every day, I benefit from tools like $TOOL, which show how shared knowledge can empower people." >> "$OUTPUT"
echo "If given the chance, I would build and freely share $BUILD so that others can learn, improve it, and use it without barriers." >> "$OUTPUT"
echo "To me, open source is not just about code — it is about trust, collaboration, and creating technology that belongs to everyone." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated by $(whoami) on $DATE" >> "$OUTPUT"

echo ""
echo "Manifesto saved to $OUTPUT"
echo ""
cat "$OUTPUT"
